/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Metodos.Imagenes;
import Metodos.MEquipos;
import User.Jugador;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author allil
 */
public class ventanaInfoE extends javax.swing.JFrame {
    
    private String codEquipo; // Atributo para almacenar el código del equipo seleccionado
    
    /**
     * Creates new form ventanaInfoE
     */
    public ventanaInfoE(String codEquipo) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Train Volley");
        // Cargar una imagen como icono desde el paquete "img" y establecerla en la ventana
        ImageIcon icono = new ImageIcon(getClass().getResource("/img/Logon_sinFondo.png"));
        this.setIconImage(icono.getImage());
        Imagenes icon = new Imagenes();
        System.out.println("Código de equipo SELECCIONADO: " + codEquipo);
        this.codEquipo = codEquipo; // Almacena el código del equipo seleccionado
        
               
       MEquipos metodos = new MEquipos();
        String[] datosEquipo = metodos.cargarEquipo(codEquipo);
        if (datosEquipo != null) {
            jNombreE.setText(datosEquipo[0]);
            jCodigoE.setText(codEquipo);
            jTipoE.setText(datosEquipo[1]);
            jCantJ.setText(datosEquipo[2]);
            
        }

        
        // Panel para mostrar los botones de jugadores
        jListaJ.setLayout(new BoxLayout(jListaJ, BoxLayout.Y_AXIS));
        jListaJ.setBorder(new EmptyBorder(10, 10, 10, 10));
        add(new JScrollPane(jListaJ), BorderLayout.CENTER);
        
        List<Jugador> jugadoresEquipo = metodos.Jugadores(codEquipo);
        System.out.println("Cantidad de jugadores en la lista: " + jugadoresEquipo.size()); // Agrega esta línea

        for (Jugador jugador : jugadoresEquipo) {
            JButton jugadorButton = new JButton(jugador.getNombreCompletoJ());
            jugadorButton.setPreferredSize(new Dimension(120, 40));
            jugadorButton.setMargin(new Insets(10, 10, 10, 10));
            jugadorButton.setBackground(new Color(55, 100, 121));
            jugadorButton.setForeground(Color.WHITE);


            jugadorButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Aquí puedes agregar la lógica para manejar el evento de clic en el botón del jugador
                    System.out.println("Jugador seleccionado: " + jugador.getNombreCompletoJ());
                    // Puedes abrir la ventana del perfil del jugador aquí si es necesario
                }
            });

            jListaJ.add(jugadorButton);
            
            
        }

        jListaJ.revalidate();
        jListaJ.repaint();
        

    }
    
    public ventanaInfoE() {
    }

    
   

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInfoE = new javax.swing.JPanel();
        jListaJ = new javax.swing.JPanel();
        jNombreE = new javax.swing.JLabel();
        jCodigoE = new javax.swing.JLabel();
        jTipoE = new javax.swing.JLabel();
        jCantJ = new javax.swing.JLabel();
        jAsistencia = new javax.swing.JButton();
        jAgregarEstudiante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInfoE.setBackground(new java.awt.Color(255, 255, 255));
        jInfoE.setForeground(new java.awt.Color(204, 204, 255));
        jInfoE.setOpaque(false);

        jListaJ.setBackground(new java.awt.Color(153, 0, 0));
        jListaJ.setLayout(new javax.swing.BoxLayout(jListaJ, javax.swing.BoxLayout.LINE_AXIS));

        jNombreE.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jNombreE.setText("Nombre Equipo:");

        jCodigoE.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jCodigoE.setText("Codigo:");

        jTipoE.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jTipoE.setText("Tipo de Equipo");

        jCantJ.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jCantJ.setText("Cjugadore");

        jAsistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Asistencias.png"))); // NOI18N
        jAsistencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jAgregarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AgregarEstudiante.png"))); // NOI18N
        jAgregarEstudiante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jAgregarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarEstudianteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Información del Equipo");

        javax.swing.GroupLayout jInfoELayout = new javax.swing.GroupLayout(jInfoE);
        jInfoE.setLayout(jInfoELayout);
        jInfoELayout.setHorizontalGroup(
            jInfoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jListaJ, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jInfoELayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jInfoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInfoELayout.createSequentialGroup()
                        .addGroup(jInfoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCodigoE, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNombreE))
                        .addGap(19, 19, 19)
                        .addComponent(jAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInfoELayout.createSequentialGroup()
                        .addGroup(jInfoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTipoE)
                            .addComponent(jCantJ, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jAgregarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jInfoELayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jInfoELayout.setVerticalGroup(
            jInfoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInfoELayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInfoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInfoELayout.createSequentialGroup()
                        .addComponent(jCodigoE)
                        .addGap(16, 16, 16)
                        .addComponent(jNombreE))
                    .addGroup(jInfoELayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jInfoELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInfoELayout.createSequentialGroup()
                        .addComponent(jTipoE)
                        .addGap(16, 16, 16)
                        .addComponent(jCantJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jAgregarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jListaJ, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jInfoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 470, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/RFondo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 800, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAgregarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarEstudianteActionPerformed
        ventanaRJugador frame = new ventanaRJugador(codEquipo);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jAgregarEstudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaInfoE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaInfoE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaInfoE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaInfoE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaInfoE();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAgregarEstudiante;
    private javax.swing.JButton jAsistencia;
    private javax.swing.JLabel jCantJ;
    private javax.swing.JLabel jCodigoE;
    private javax.swing.JPanel jInfoE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jListaJ;
    private javax.swing.JLabel jNombreE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTipoE;
    // End of variables declaration//GEN-END:variables
}
