/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Metodos.Imagenes;
import Metodos.ValidarDatos;
import User.Docente;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author allil
 */
public class ventanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form ventanaLogin
     */
    public ventanaLogin() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Train Volley");
        // Cargar una imagen como icono desde el paquete "img" y establecerla en la ventana
        ImageIcon icono = new ImageIcon(getClass().getResource("/img/Logon_sinFondo.png"));
        this.setIconImage(icono.getImage());
        
        //Redimensionar el icono
        Imagenes iconVolver = new Imagenes();
        iconVolver.setIcono("/img/flecha.png", 40, 40); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Aceptar = new javax.swing.JButton();
        txt_Contra = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Crede = new javax.swing.JPasswordField();
        txt_Correo = new javax.swing.JTextField();
        jHyperR = new javax.swing.JLabel();
        btn_Volver = new javax.swing.JButton();
        FondoL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesión");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jLabel2.setText("Correo Electrónico");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 120, -1));

        btn_Aceptar.setBackground(new java.awt.Color(250, 190, 149));
        btn_Aceptar.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        btn_Aceptar.setText("Iniciar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 103, 32));
        jPanel2.add(txt_Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 140, 31));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jLabel4.setText("Credencial");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 210, 100, -1));

        txt_Crede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CredeActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Crede, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 140, 30));

        txt_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CorreoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 112, 140, 31));

        jHyperR.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jHyperR.setForeground(new java.awt.Color(79, 86, 89));
        jHyperR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHyperR.setText("Registrarse");
        jHyperR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHyperRMouseClicked(evt);
            }
        });
        jPanel2.add(jHyperR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 100, -1));

        btn_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/flecha.png"))); // NOI18N
        btn_Volver.setPreferredSize(new java.awt.Dimension(70, 71));
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 46, 41));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 460, 380));

        FondoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/RFondo.png"))); // NOI18N
        FondoL.setText("jLabel4");
        jPanel1.add(FondoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        String correoInstitucional = txt_Correo.getText();
        String contra = txt_Contra.getText();
        String credenciales = txt_Crede.getText();
        
        ValidarDatos retornarid = new ValidarDatos();
        String id = retornarid.obtenerIdUsuarioDesdeArchivo(correoInstitucional, credenciales, contra);
        
        ValidarDatos validar = new ValidarDatos();
        if (validar.validarDatosInicio(correoInstitucional, contra, credenciales)){
            
            //Objeto Docente
            Docente nuevoDocente = new Docente(correoInstitucional, credenciales, contra);
            //ir al home/menú
            JOptionPane.showMessageDialog(this, "Bienvenido(a), docente: " + validar.retornarNombreC(correoInstitucional, contra, credenciales));
            Menu frame = new Menu(id);
            frame.setVisible(true);
            this.setVisible(false);

            
            txt_Crede.setText("");
            txt_Correo.setText("");
            txt_Contra.setText("");
            
        }else{
            
        }
        

    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void txt_CredeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CredeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CredeActionPerformed

    private void txt_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CorreoActionPerformed

    private void jHyperRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHyperRMouseClicked
        ventanaRegistro frame = new ventanaRegistro();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jHyperRMouseClicked

    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        ventanaInicial frame = new ventanaInicial();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoL;
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JLabel jHyperR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txt_Contra;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JPasswordField txt_Crede;
    // End of variables declaration//GEN-END:variables
}
